name: build shit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: "zulu"
        cache: gradle
    - name: Build with gradle
      run: ./gradlew build --no-daemon
    - name: date
      run: echo "date=$(date +%Y-%m-%d-%H-%M-%S)" >> "$GITHUB_OUTPUT"
      id: date

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.date.outputs.date }}
        body: "diff the file urself for changelog"
        name: artifact
        commit: ${{ github.sha }}
        artifacts: build/libs/*.jar

