name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        cache: gradle
    - name: Build with gradle
      run: ./gradlew build --no-daemon

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        body: "diff the file urself for change log"
        name: artifact
        commit: ${{ github.sha }}
        path: build/libs/*.jar

